// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectState = { video_path: string | null, stt_status: STTStatus, stt_error_message: string | null, stt_progress: number, translation_status: TranslationStatus, translation_progress: number, results: Array<STTResult>, target_language: string, };

export type STTResult = { start: number, end: number, text: string, translation: string | null, };

export type STTStatus = "idle" | "loading_model" | "transcribing" | "completed" | "error";

export type TranslationStatus = "idle" | "translating" | "completed" | "error";
