// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	lookupWord: (text: string) => typedError<LookupResult, string>(__TAURI_INVOKE("lookup_word", { text })),
	getFurigana: (text: string) => typedError<FuriganaToken[], string>(__TAURI_INVOKE("get_furigana", { text })),
	startSttJob: (videoPath: string, modelSize: string, language: string, vadEngine: string, mssEngine: string, mssModel: string, useBatch: boolean, batchSize: number, enableTranslation: boolean) => typedError<string, string>(__TAURI_INVOKE("start_stt_job", { videoPath, modelSize, language, vadEngine, mssEngine, mssModel, useBatch, batchSize, enableTranslation })),
	cancelSttJob: (jobId: string) => typedError<null, string>(__TAURI_INVOKE("cancel_stt_job", { jobId })),
	importSttResults: (results: STTResult[]) => typedError<null, string>(__TAURI_INVOKE("import_stt_results", { results })),
	startTranslation: () => typedError<null, string>(__TAURI_INVOKE("start_translation")),
	runAgentTask: (agentType: AgentType, payloadJson: string) => typedError<string, string>(__TAURI_INVOKE("run_agent_task", { agentType, payloadJson })),
	getAppState: () => typedError<ProjectState, string>(__TAURI_INVOKE("get_app_state")),
};

/* Types */
export type AgentType = "TranslatorAgent";

export type DictionaryEntry = {
	id: string,
	headwords: string[],
	pronunciations: string[],
	tags: string[],
	glossary: string[],
};

export type FuriganaToken = {
	surface: string,
	reading: string | null,
};

export type LookupResult = {
	original_text: string,
	token: string,
	base_form: string,
	reading: string | null,
	entries: DictionaryEntry[],
};

export type PipelineTask = {
	task_type: TaskType,
	status: TaskStatus,
	progress: number | null,
	error_message: string | null,
};

export type ProjectState = {
	video_path: string | null,
	tasks: PipelineTask[],
	results: STTResult[],
	target_language: string,
	vocals_audio_path: string | null,
	background_audio_path: string | null,
};

export type STTResult = {
	start: number | null,
	end: number | null,
	text: string,
	translation: string | null,
	words: WordTiming[] | null,
};

export type TaskStatus = "pending" | "running" | "completed" | "error" | "cancelled";

export type TaskType = "mss" | "vad" | "stt" | "translation";

export type WordTiming = {
	text: string,
	start: number | null,
	end: number | null,
	probability: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

