// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	lookupWord: (text: string) => typedError<LookupResult, string>(__TAURI_INVOKE("lookup_word", { text })),
	runStt: (videoPath: string, modelSize: string) => typedError<null, string>(__TAURI_INVOKE("run_stt", { videoPath, modelSize })),
	runAgentTask: (agentType: AgentType, payloadJson: string) => typedError<string, string>(__TAURI_INVOKE("run_agent_task", { agentType, payloadJson })),
	getAppState: () => typedError<ProjectState, string>(__TAURI_INVOKE("get_app_state")),
	startTranslation: () => typedError<null, string>(__TAURI_INVOKE("start_translation")),
};

/* Types */
export type AgentType = "TranslatorAgent";

export type DictionaryEntry = {
	id: string,
	kanji: string[],
	kana: string[],
	glossary: string[],
};

export type LookupResult = {
	original_text: string,
	token: string,
	base_form: string,
	reading: string,
	entries: DictionaryEntry[],
};

export type ProjectState = {
	video_path: string | null,
	stt_status: STTStatus,
	stt_progress: number | null,
	translation_status: TranslationStatus,
	translation_progress: number | null,
	results: STTResult[],
	target_language: string,
};

export type STTResult = {
	start: number | null,
	end: number | null,
	text: string,
	translation: string | null,
};

export type STTStatus = "idle" | "loading_model" | "transcribing" | "completed" | "error";

export type TranslationStatus = "idle" | "translating" | "completed" | "error";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

